import type { Metadata } from 'next';
import '../styles/globals.css';
import { Header } from '@/components/shared/header/component';
import { Providers } from '@/components/providers/Providers';
import Aside from '@/components/shared/aside/component';

export const metadata: Metadata = {
  title: 'RT Pepper',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="grid grid-cols-[1fr_4fr] grid-rows-[auto_1fr] h-screen">
        <Providers>
          <Aside />
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
