import type { Metadata } from 'next';
import { Header } from '@/components/shared/header/component';
import { Providers } from '@/components/providers/Providers';
import Aside from '@/components/shared/aside/component';
import '../../styles/globals.css';

export const metadata: Metadata = {
  title: 'RT Pepper',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'en-US' }, { lang: 'de' }];
}

export default function RootLayout({
  children,
  lang,
}: Readonly<{
  children: React.ReactNode;
  lang: string;
}>) {
  return (
    <html lang={lang} suppressHydrationWarning={true}>
      <body className="grid grid-cols-[1fr_4fr] grid-rows-[auto_1fr] h-screen">
        <Providers>
          <Aside />
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
