import type { Metadata } from 'next';
import { Header } from '@/app/components/shared/header/component';
import { Providers } from '@/app/components/providers/Providers';
import Aside from '@/app/components/shared/aside/component';
import '../../styles/globals.css';
import { getDictionary } from '../dictionaries';
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: 'RT Pepper',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'ru' }, { lang: 'es' }];
}

type Props = {
  children: React.ReactNode;
  params: { lang: string };
};

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<Props>) {
  const dict = await getDictionary(lang);

  return (
    <html lang={lang} suppressHydrationWarning={true}>
      <body className="grid grid-cols-[1fr_4fr] grid-rows-[auto_1fr] h-screen">
      <NextTopLoader color='#BC6C25'/>
        <Providers>
          <Aside lang={lang} dict={dict} />
          <Header lang={lang} dict={dict} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
