import type { Metadata } from 'next';
import { Header } from '@/components/shared/header/component';
import { Providers } from '@/components/providers/Providers';
import Aside from '@/components/shared/aside/component';
import '../../styles/globals.css';
import { getDictionary } from '../dictionaries';

export const metadata: Metadata = {
  title: 'RT Pepper',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'en-US' }, { lang: 'nl' }];
}

type Props = {
  children: React.ReactNode;
  params: { lang: string };
};

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<Props>) {
  
  const dict = await getDictionary(lang);
  console.log(dict);

  return (
    <html lang={lang} suppressHydrationWarning={true}>
      <body className="grid grid-cols-[1fr_4fr] grid-rows-[auto_1fr] h-screen">
        <Providers>
          <Aside lang={lang} dict={dict} />
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
